### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mariocapellari** [dreamview-studios-inc/ADSK-SA-2020-0003-Tools#2]
I am getting the following error message when executing dephade.exe as Administrator (same error when executing as regular user) on my personal PC.

Command:
```
C:\Users\DreamView\Downloads\dephade.exe -c c:\
```

Error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa37f2d]
```

Output:
```
C:\WINDOWS\system32>c:\Users\DreamView\Downloads\dephage.exe -c c:\
Processing folder: c:\
Processing maya folder: C:\Users\DreamView/Documents/maya/scripts

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0xa37f2d]

goroutine 1 [running]:
main.processFile(0xc000257d60, 0x9a, 0x0, 0x0, 0xa920e8, 0xc00007c7b0, 0x0, 0x0)
        /home/bryan/src/ADSK-SA-2020-0003-Tools/main.go:91 +0x2d
path/filepath.walk(0xc0000a0120, 0x88, 0xa93078, 0xc0002cd030, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:434 +0x226
path/filepath.walk(0xc000208580, 0x77, 0xa93078, 0xc0002fa770, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc000089780, 0x73, 0xa93078, 0xc00060e0e0, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc00049f260, 0x6f, 0xa93078, 0xc0004a6310, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc00049f030, 0x68, 0xa93078, 0xc0004a6230, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc0003f3680, 0x5d, 0xa93078, 0xc000419b90, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc00000e480, 0x29, 0xa93078, 0xc00045c620, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc00041cf40, 0x20, 0xa93078, 0xc0002cca10, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc00041cee0, 0x1a, 0xa93078, 0xc0002cc9a0, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc000212138, 0x12, 0xa93078, 0xc00060fa40, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc00015ab00, 0x8, 0xa93078, 0xc0001840e0, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc0000120c0, 0x3, 0xa93078, 0xc000122070, 0xa72978, 0x0, 0xa6865d)
        /usr/local/go/src/path/filepath/path.go:438 +0x31b
path/filepath.Walk(0xc0000120c0, 0x3, 0xa72978, 0x0, 0x0)
        /usr/local/go/src/path/filepath/path.go:501 +0x125
main.main()
        /home/bryan/src/ADSK-SA-2020-0003-Tools/main.go:83 +0x458
```

System configuration:
- Windows 10 Home 20H2 19042.985
- i7 32 GB RAM

**Comment by bryanweingarten** [comment]
@mariocapellari please try again using v1.2.1

**Comment by bryanweingarten** [comment]
Closing this issue. We are now at version v1.3.0.  If this issue happens happens again, please reopen.
